LP_PC_COM_DALI_DOWN_CHECK_E	0x1002	检查设备（简单查询）
LP_PC_COM_DALI_DOWN_EXTEND_CHECK_E	0x1003	搜索设备（完整搜索）
LP_PC_COM_DALI_DOWN_SEARCH_AGAIN_E	0x1004	继续搜索（分页）
LP_PC_COM_DALI_DOWN_READ_INFO_E	0x1006	读取设备信息
LP_PC_COM_DALI_DOWN_WRITE_INFO_E	0x1007	写设备信息
LP_PC_COM_DALI_DOWN_SET_DAPC_E	0x100C	设置亮度

//特殊指令
关键 DALI 命令
命令	字节	功能
INITIALISE	0xA5	进入初始化模式
RANDOMISE	0xA7	生成随机地址（设备首次通电时执行）
SEARCHADDRH/M/L	0xB1/0xB3/0xB5	设置搜索地址（高/中/低字节）
COMPARE	0xA9	比较随机地址与搜索地址
VERIFY_SHORT_ADDRESS	0xB9	检查设备是否有地址
PROGRAM_SHORT_ADDRESS	0xB7	写入短地址